# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96057026110583b971690e2f62631ecc665a5a433b976892e166efbf6495acde3560ca3ffde9455dc9197666e5e72a451512ccb61664418dfa4134e0318fd17d

test:
  secret_key_base: 3da4030f3dd71f9fe69cd8a81445d0b8b80d391a3b92b7bd5bac649c85ef3564d22c8f7d039fbfef26875b25977aed95976997c8cf193aab2538c06e27567b1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
